// Generated by CIRCT firtool-1.44.0
module SevenSegmentDisplay(	// @[<stdin>:3:10]
  input  [3:0] io_in,	// @[playground/src/encode83.scala:7:16]
  input        io_en,	// @[playground/src/encode83.scala:7:16]
  output [6:0] io_out	// @[playground/src/encode83.scala:7:16]
);

  reg [6:0] casez_tmp;	// @[playground/src/encode83.scala:13:47]
  always_comb begin	// @[playground/src/encode83.scala:13:47]
    casez (io_in)	// @[playground/src/encode83.scala:13:47]
      4'b0000:
        casez_tmp = 7'h40;	// @[playground/src/encode83.scala:13:47]
      4'b0001:
        casez_tmp = 7'h79;	// @[playground/src/encode83.scala:13:47]
      4'b0010:
        casez_tmp = 7'h24;	// @[playground/src/encode83.scala:13:47]
      4'b0011:
        casez_tmp = 7'h30;	// @[playground/src/encode83.scala:13:47]
      4'b0100:
        casez_tmp = 7'h19;	// @[playground/src/encode83.scala:13:47]
      4'b0101:
        casez_tmp = 7'h12;	// @[playground/src/encode83.scala:13:47]
      4'b0110:
        casez_tmp = 7'h2;	// @[playground/src/encode83.scala:13:47]
      4'b0111:
        casez_tmp = 7'h78;	// @[playground/src/encode83.scala:13:47]
      4'b1000:
        casez_tmp = 7'h0;	// @[playground/src/encode83.scala:13:47]
      4'b1001:
        casez_tmp = 7'h10;	// @[playground/src/encode83.scala:13:47]
      4'b1010:
        casez_tmp = 7'h8;	// @[playground/src/encode83.scala:13:47]
      4'b1011:
        casez_tmp = 7'h3;	// @[playground/src/encode83.scala:13:47]
      4'b1100:
        casez_tmp = 7'h46;	// @[playground/src/encode83.scala:13:47]
      4'b1101:
        casez_tmp = 7'h21;	// @[playground/src/encode83.scala:13:47]
      4'b1110:
        casez_tmp = 7'h6;	// @[playground/src/encode83.scala:13:47]
      default:
        casez_tmp = 7'hE;	// @[playground/src/encode83.scala:13:47]
    endcase	// @[playground/src/encode83.scala:13:47]
  end // always_comb
  assign io_out = io_en ? casez_tmp : 7'h0;	// @[<stdin>:3:10, playground/src/encode83.scala:13:{18,47}]
endmodule

module encode83(	// @[<stdin>:41:10]
  input        clock,	// @[<stdin>:42:11]
               reset,	// @[<stdin>:43:11]
  input  [7:0] io_in,	// @[playground/src/encode83.scala:35:16]
  output [6:0] io_out_seg,	// @[playground/src/encode83.scala:35:16]
  output [2:0] io_out_bin,	// @[playground/src/encode83.scala:35:16]
  output       io_ind	// @[playground/src/encode83.scala:35:16]
);

  wire [2:0] _io_out_bin_T_43 =
    io_in[7]
      ? 3'h0
      : io_in[6]
          ? 3'h1
          : io_in[5]
              ? 3'h2
              : io_in[4] ? 3'h3 : io_in[3] ? 3'h4 : io_in[2] ? 3'h5 : {2'h3, ~(io_in[1])};	// @[playground/src/encode83.scala:42:43, src/main/scala/chisel3/util/Mux.scala:50:70]
  SevenSegmentDisplay seg (	// @[playground/src/encode83.scala:45:21]
    .io_in  ({1'h0, ~_io_out_bin_T_43}),	// @[playground/src/encode83.scala:42:{19,43}, :46:15, src/main/scala/chisel3/util/Mux.scala:50:70]
    .io_en  (|io_in),	// @[playground/src/encode83.scala:43:21]
    .io_out (io_out_seg)
  );
  assign io_out_bin = ~_io_out_bin_T_43;	// @[<stdin>:41:10, playground/src/encode83.scala:42:19, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_ind = |io_in;	// @[<stdin>:41:10, playground/src/encode83.scala:43:21]
endmodule

