// Generated by CIRCT firtool-1.44.0
module mux241(	// @[<stdin>:3:10]
  input        clock,	// @[<stdin>:4:11]
               reset,	// @[<stdin>:5:11]
  input  [1:0] io_in_0,	// @[playground/src/mux241.scala:4:16]
               io_in_1,	// @[playground/src/mux241.scala:4:16]
               io_in_2,	// @[playground/src/mux241.scala:4:16]
               io_in_3,	// @[playground/src/mux241.scala:4:16]
               io_sel,	// @[playground/src/mux241.scala:4:16]
  output [1:0] io_out	// @[playground/src/mux241.scala:4:16]
);

  reg [1:0] casez_tmp;	// @[playground/src/mux241.scala:10:42]
  always_comb begin	// @[playground/src/mux241.scala:10:42]
    casez (io_sel)	// @[playground/src/mux241.scala:10:42]
      2'b00:
        casez_tmp = io_in_0;	// @[playground/src/mux241.scala:10:42]
      2'b01:
        casez_tmp = io_in_1;	// @[playground/src/mux241.scala:10:42]
      2'b10:
        casez_tmp = io_in_2;	// @[playground/src/mux241.scala:10:42]
      default:
        casez_tmp = io_in_3;	// @[playground/src/mux241.scala:10:42]
    endcase	// @[playground/src/mux241.scala:10:42]
  end // always_comb
  assign io_out = casez_tmp;	// @[<stdin>:3:10, playground/src/mux241.scala:10:42]
endmodule

